- hosts: all
  become: true
  tasks:
    - name: alterando nome dos hosts
      hostname:
        name: "{{ new_hostname }}"
        
    - name: criando diretório de config do Docker
      file: path=/etc/docker state=directory

    - name: trocando driver do Docker para systemd
      copy:
        dest: "/etc/docker/daemon.json"
        content: |
          {
          "exec-opts": ["native.cgroupdriver=systemd"]
          }

    - name: instalando Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: instalando APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: adicionando Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: adicionando Kubernetes APT repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: instalando kubelet
      apt:
        name: kubelet=1.22.4-00
        state: present
        update_cache: true

    - name: instalando kubeadm
      apt:
        name: kubeadm=1.22.4-00
        state: present

- hosts: masters
  become: true
  tasks:
  - name: instalando kubectl
    apt:
      name: kubectl=1.22.4-00
      state: present
      force: yes